#Generate layer for the lambda function

#Remove the container first(if it exists)
docker rm layer-container

#Build the image from the docker file (chose base-layer as its name in this case)
docker build -t base-layer .

#Spinned up container from the image and renamed to layer-container instead of uid generated by docker.
docker run --name layer-container base-layer

#copy the generated zip artifact so our CDK can use it
docker cp layer-container:layer.zip . && echo "Created layer.zip with updated base layer"
